# Generated by Django 4.0.4 on 2022-05-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='First Name', max_length=100)),
                ('lastName', models.CharField(help_text='Last Name', max_length=1000)),
                ('email', models.CharField(help_text='email', max_length=100)),
                ('Subject', models.TextField(help_text='Subject', max_length=300)),
                ('Body', models.TextField(help_text='Body', max_length=1000)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label Name', max_length=100)),
                ('description', models.CharField(help_text='Label Description', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label Name', max_length=100)),
                ('labelName', models.CharField(help_text='Label Name', max_length=100)),
                ('description', models.CharField(help_text='Label Description', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project Name', max_length=100)),
                ('summary', models.TextField(help_text='Project Summary', max_length=1000)),
                ('github', models.URLField(help_text='Project Github', max_length=300)),
                ('Image', models.ImageField(upload_to='media/projectImages/')),
            ],
        ),
        migrations.CreateModel(
            name='projectLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelName', models.CharField(help_text='Label Name', max_length=100)),
                ('projectName', models.CharField(help_text='Project Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project Name', max_length=100)),
                ('Image', models.FileField(upload_to='')),
            ],
        ),
    ]
