# Generated by Django 4.0.4 on 2022-04-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label Name', max_length=100)),
                ('description', models.CharField(help_text='Label Description', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project Name', max_length=100)),
                ('summary', models.CharField(help_text='Project Summary', max_length=1000)),
                ('github', models.CharField(help_text='Project Github', max_length=300)),
                ('labels', models.ManyToManyField(help_text='Project Labels', to='mainApp.label')),
            ],
        ),
    ]
