# Generated by Django 4.0.4 on 2022-05-15 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='Body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='Subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='firstName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='lastName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
